### ISSUE TITLE
Image thumbnails disapearing backend

### ISSUE THREAD

**Issue by wroughtec** [idseefeld/UmbracoAzureBlobStorage#6]
After a few days after adding the images to a Storage blob on Azure the thumbnails start to disappear on the backend so the images appear as broken links even though the image is still available in the console I am getting the following error:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.domain.com/umbraco/backoffice/UmbracoApi/Images/GetBigThumbnail?originalImagePath=https%3A%2F%2Faz695284.vo.msecnd.net%2Fmedia%2F1001%2Fft-bannerpiste-1140.png

If I strip out the the getbigthumbnail and just use:
az695284.vo.msecnd.net/media/1001/ft-bannerpiste-1140.png

the image is available and is showing on the front end although every now and then the images disappear from there to any thoughts is this being caused by the plugin or is something else happening?

Anyone else experienced this

**Comment by idseefeld** [comment]
Hi,
looks like you used a CDN endpoint domain in the blob configuration (rootUrl). 
But you should use the Blob Storage domain something like http://[myAccountName].blob.core.windows.net/
CDN endpoints do heavy caching - indead that is their main purpose ;-)
Especially in the Umbraco back office you don't want this kind of caching!
Currently the only solution to use the CDN endpoint in your frontend views (where it might makes sense) is to do a simple replace of the domain name.
Yours
Dirk
