### ISSUE TITLE
How do I run the tests?

### ISSUE THREAD

**Issue by warrenbuckley** [idseefeld/UmbracoAzureBlobStorage#7]
Hi Dirk,
This looks useful but I am not sure how I run the unit tests, can you provide any advice please?

Cheers,
Warren

**Comment by idseefeld** [comment]
Hi Warren,
I cannot run the tests too. But I am asking Lars-Erik who initially implemented the test.
So I come back to you when I have the answer!
Yours
Dirk

**Comment by idseefeld** [comment]
Hi Warren,
meanwhile I figured it out. All you have to do is adding the extension "NUnit Test Adapter" to your Visual Studio toolbox. I have just tested this with VStudio 2012.
Tool Docu is here: http://nunit.org/index.php?p=vsTestAdapter&r=2.6.3
My result is one failed test - ups! - and 27 passed tests.

Dirk

**Comment by idseefeld** [comment]
I added some further hints to the README.md
